export interface ProductPreset {
  id: string;
  name: string;
  icon: string;
  unitName: string; // '개', '캔', '병', '판', '롤', '봉지'
  specLabel: string; // '210g', '355ml', '120g', '30구'
  defaultPrice: number;
  defaultQty: number;
  specSize: number; // 210 (g), 355 (ml), 120 (g), 1 (개)
  topDealPrice: number; // 개당 역대급 최저가 기준 단가
  goodDealPrice: number; // 개당 무난한 핫딜 기준 단가
  fairDealPrice: number; // 개당 아쉬운 일반 마트가 단가
  unitLabel: string; // '100g당', '100ml당', '1개당'
  searchQuery: string;
}

export const PRESETS: ProductPreset[] = [
  {
    id: 'hetbahn',
    name: '즉석밥(햇반)',
    icon: '🍚',
    unitName: '개',
    specLabel: '210g 기본',
    defaultPrice: 26900,
    defaultQty: 36,
    specSize: 210,
    topDealPrice: 720,
    goodDealPrice: 850,
    fairDealPrice: 980,
    unitLabel: '100g당',
    searchQuery: '햇반 210g 36개 핫딜',
  },
  {
    id: 'ottogi_rice',
    name: '즉석밥(오뚜기)',
    icon: '🍚',
    unitName: '개',
    specLabel: '210g 기본',
    defaultPrice: 15400,
    defaultQty: 24,
    specSize: 210,
    topDealPrice: 650,
    goodDealPrice: 780,
    fairDealPrice: 900,
    unitLabel: '100g당',
    searchQuery: '오뚜기밥 210g 24개 핫딜',
  },
  {
    id: 'misik_rice',
    name: '즉석밥(더미식)',
    icon: '🍚',
    unitName: '개',
    specLabel: '210g 기본',
    defaultPrice: 21900,
    defaultQty: 24,
    specSize: 210,
    topDealPrice: 850,
    goodDealPrice: 990,
    fairDealPrice: 1150,
    unitLabel: '100g당',
    searchQuery: '더미식 백미밥 핫딜',
  },
  {
    id: 'coke_zero',
    name: '코카콜라(제로)',
    icon: '🥤',
    unitName: '캔',
    specLabel: '355ml 뚱캔',
    defaultPrice: 18900,
    defaultQty: 24,
    specSize: 355,
    topDealPrice: 680,
    goodDealPrice: 850,
    fairDealPrice: 1050,
    unitLabel: '100ml당',
    searchQuery: '코카콜라 제로 355ml 24캔 핫딜',
  },
  {
    id: 'coke_original',
    name: '코카콜라(일반)',
    icon: '🥤',
    unitName: '캔',
    specLabel: '355ml 뚱캔',
    defaultPrice: 20900,
    defaultQty: 24,
    specSize: 355,
    topDealPrice: 750,
    goodDealPrice: 920,
    fairDealPrice: 1100,
    unitLabel: '100ml당',
    searchQuery: '코카콜라 355ml 24캔 핫딜',
  },
  {
    id: 'pepsi_zero',
    name: '펩시(제로 라임)',
    icon: '🥤',
    unitName: '캔',
    specLabel: '355ml 뚱캔',
    defaultPrice: 15900,
    defaultQty: 24,
    specSize: 355,
    topDealPrice: 580,
    goodDealPrice: 720,
    fairDealPrice: 900,
    unitLabel: '100ml당',
    searchQuery: '펩시 제로 라임 355ml 24캔 핫딜',
  },
  {
    id: 'shin_ramen',
    name: '신라면(120g)',
    icon: '🍜',
    unitName: '봉지',
    specLabel: '120g 표준',
    defaultPrice: 15200,
    defaultQty: 20,
    specSize: 120,
    topDealPrice: 680,
    goodDealPrice: 820,
    fairDealPrice: 980,
    unitLabel: '100g당',
    searchQuery: '신라면 20봉지 핫딜',
  },
  {
    id: 'jin_ramen',
    name: '진라면(120g)',
    icon: '🍜',
    unitName: '봉지',
    specLabel: '120g 표준',
    defaultPrice: 11800,
    defaultQty: 20,
    specSize: 120,
    topDealPrice: 520,
    goodDealPrice: 650,
    fairDealPrice: 780,
    unitLabel: '100g당',
    searchQuery: '진라면 매운맛 20봉지 핫딜',
  },
  {
    id: 'eggs',
    name: '계란(30구 판란)',
    icon: '🥚',
    unitName: '구',
    specLabel: '특란 30구',
    defaultPrice: 6900,
    defaultQty: 30,
    specSize: 1,
    topDealPrice: 180,
    goodDealPrice: 230,
    fairDealPrice: 280,
    unitLabel: '1구당',
    searchQuery: '계란 30구 특란 핫딜',
  },
  {
    id: 'seoul_milk',
    name: '서울우유(1L)',
    icon: '🥛',
    unitName: '팩',
    specLabel: '1,000ml 팩',
    defaultPrice: 2890,
    defaultQty: 1,
    specSize: 1000,
    topDealPrice: 2400,
    goodDealPrice: 2700,
    fairDealPrice: 3000,
    unitLabel: '100ml당',
    searchQuery: '서울우유 1L 핫딜',
  },
  {
    id: 'tissue',
    name: '롤휴지(30롤)',
    icon: '🧻',
    unitName: '롤',
    specLabel: '3겹 30롤',
    defaultPrice: 14900,
    defaultQty: 30,
    specSize: 1,
    topDealPrice: 380,
    goodDealPrice: 500,
    fairDealPrice: 650,
    unitLabel: '1롤당',
    searchQuery: '3겹 롤휴지 30롤 핫딜',
  },
  {
    id: 'samdasoo',
    name: '삼다수 생수(2L)',
    icon: '💧',
    unitName: '병',
    specLabel: '2L 6병',
    defaultPrice: 5800,
    defaultQty: 6,
    specSize: 2000,
    topDealPrice: 600,
    goodDealPrice: 800,
    fairDealPrice: 1050,
    unitLabel: '100ml당',
    searchQuery: '삼다수 2L 6병 핫딜',
  },
];
